= Transitietechnieken

The energy transition at the lower voltage (LV) level is steadily progressing
and is accompanied by a number of complications, in which the data product
_Energy Transition Techniques_ plays an enabling role. Part of the solution in
better utalisation of the existing grid is to better align peaks in the demand
and supply of electricity. This data product provides insight into energy usage
behind the meter.

.Data Product
[d2,svg,theme=4]
----
grid-rows: 4
grid-columns: 4

horizontal-gap: 160
vertical-gap: 80

vars: {
  d2-config: {
    pad: 20
  }
}

ResourcesDataSet.class: dataset
TopologicalNode.class: grid
MktConnectivityNode.class: market
RegisteredResource.class: market
ResourceCapacity.class: market

1.class: empty
Terminal.class: grid
2.class: empty
3.class: empty
4.class: empty

5.class: empty
EnergyConsumer.class: grid
6.class: empty
7.class: empty
8.class: empty

9.class: empty
MarketEvaluationPoint.class: market
Location.class: enterprise
10.class: empty
11.class: empty

ResourcesDataSet -> TopologicalNode: ""
TopologicalNode -> MktConnectivityNode: "connectivity_node"
MktConnectivityNode -> RegisteredResource: "registered_resource"
RegisteredResource -> ResourceCapacity: "resource_capacity"
TopologicalNode -> Terminal: "terminals"
EnergyConsumer -> MarketEvaluationPoint: "usage_points"
MarketEvaluationPoint -> Location: "usage_point_location"
Terminal -> EnergyConsumer: "conducting_equipment"

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
  }
}

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
}
----

== Use cases

This information model supports two separate use cases for providing
information:

* enumeration of ``RegisteredResource``s for one or more ``MktConnectivityNode``s;
* aggregation of ``RegisteredResource``s, where the ``ResourceCapacity``s
  describe an aggregated capacity.

== Additional artifacts

* xref:schema:attachment$schemas/json_schema/dp_transitietechnieken.json_schema.json[JSON schema]
* xref:schema:attachment$examples/dp_transitietechnieken_enumeration.example.json[Enumeration example instance data]
* xref:schema:attachment$examples/dp_transitietechnieken_aggregation.example.json[Aggregation example instance data]
